import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dir, "..");
const bundled: Record<string, string> = {};
for (const name of readdirSync(path.join(root, "skills")).sort()) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name)) throw new Error(`Invalid skill directory '${name}'.`);
  const source = readFileSync(path.join(root, "skills", name, "SKILL.md"), "utf8");
  if (!source.startsWith(`---\nname: ${name}\n`) || !source.includes("\ndescription: ")) throw new Error(`Invalid skill frontmatter for '${name}'.`);
  if (!/\n---\n\n# [^\n]+\n\n/.test(source)) throw new Error(`Missing top-level Markdown heading for skill '${name}'.`);
  bundled[name] = source;
}
writeFileSync(path.join(root, "src/skills/bundled.ts"), `// Generated by scripts/bundle-skills.ts; edit skills/*/SKILL.md.\nexport const BUNDLED_SKILLS: Readonly<Record<string, string>> = ${JSON.stringify(bundled, null, 2)};\n`);
